Cray-HPE/csm-hotfixes

CASMREL-776-CSM12-NCN-boot-order-backport/lib/version.sh
CASMREL-776-CSM12-NCN-boot-order-backport/scripts/lib.sh
CASMREL-776-CSM12-NCN-boot-order-backport/scripts/metal-lib.sh
CASMREL-776-CSM12-NCN-boot-order-backport/scripts/mini-install.sh

This is just documentation updates for the already submitted hotfix, plus a patch from the current 1.2alpha boot code.
This adds a permalink to the official, public version of the CSM 1.2 scripts.
This also brings in the MTL-1559 fix which was merged into 1.2 NCN Boot code (0.2.21 NCN stable).

MTL-1545 doc updates

---

CASMHMS-5480-do-not-wait-for-off/README.md
CASMHMS-5480-do-not-wait-for-off/docker/index.yaml
CASMHMS-5480-do-not-wait-for-off/docker/transform.sh
CASMHMS-5480-do-not-wait-for-off/helm/index.yaml
CASMHMS-5480-do-not-wait-for-off/install-hotfix.sh
CASMHMS-5480-do-not-wait-for-off/lib/install.sh
CASMHMS-5480-do-not-wait-for-off/lib/setup-nexus.sh
CASMHMS-5480-do-not-wait-for-off/lib/version.sh

A previous mod implemented support for emulating restarts when the
hardware does not directly support it. It ended up causing every power
off to wait for the hardware to be off. This caused problems due to the
behavior change and a short timeout. Bumped the timeout from 1 minute to
15 minutes. This timeout is still site dependent.
* Resolves CASMHMS-5480 for csm 1.0.x
Tested on:
* `hela`
Were the install/upgrade based validation checks/tests run? N
Were continuous integration tests run? Y
Was an Upgrade tested?                 Y
Was a Downgrade tested?                Y
Upgraded CAPMC to fixed version, verified CAPMC returns immediately after sending power Off to target node. There were no checks by CAPMC to see if the node was off. Issues a reinit to a node and verified CAPMC waited for …

Casmhms 5480 do not wait for off

---

CASMREL-1501_FAS-Loader_BOSv2-Power/docker/index.yaml
CASMREL-1501_FAS-Loader_BOSv2-Power/helm/index.yaml
CASMREL-1501_FAS-Loader_BOSv2-Power/install-hotfix.sh

This changes the 1.3 hotfix in two ways:
1. Updates the BOS version to include the fix for [https://jira-pro.it.hpe.com:8443/browse/CASMINST-6451](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6451)
2. Modifies the install script so that it applies customization before deploying the manifest. The charts in question are not ones we typically expect to see being customized, but it's possible, so we should do it.

Update 1.3 hotfix to pull in fix for CASMINST-6451 and to apply customizations to manifest before deploy

---

CASMREL-1501_FAS-Loader_BOSv2-Power/install-hotfix.sh

I neglected to update the BOS version in the install script in my last PR. I only updated it in the index files. My testing of the install worked because the system where I tested it had both versions available, so it was able to deploy, even with this error. But it will not work on systems that don't have both, which will be most.

Update hotfix install script to use correct BOS version in manifest

---

CASMTRIAGE-5033/README.md
CASMTRIAGE-5033/lib/version.sh

Despite CSM Hotfixes using JIRA names already, the name for the QLogic hotfix has been deemed as "icky."
This renames it to match to Greg's manual rename, calling out qlogic and hotfix in the tar name.
This also updates the README so it works with the new name.

Use a nicer customer facing name

---

CASMTRIAGE-5033/install-hotfix.sh
CASMTRIAGE-5033/lib/version.sh

Update the CASMTRIAGE-5033 hotfix so that it also:
- Updates the disk bootloader
- Updates S3 and BSS
This will ensure that the patch sticks after reboots.

CASMTRIAGE-6055 Update CASMTRIAGE-5033 hotfix

---

CASMTRIAGE-5033/install-hotfix.sh
CASMTRIAGE-5033/lib/version.sh

CSM 1.4 `craycli` does NOT support multiple `--subrole` parameters.
When the hotfix is invoked, only the last `--subrole` was acknowledged. This meant that only Worker nodes were targeted for the BSS updates.
Follow up to #25

CASMTRIAGE-6055 CSM 1.4 `craycli` compatibility

---

CASMTRIAGE-5033/install-hotfix.sh

Debug `echo` commands were added in for testing the addition of the `function`, but they were supposed to be removed.

Remove debug echos

---

CASMTRIAGE-5033/install-hotfix.sh

```
ncn-m001:/mnt/developer/rusty/csm-1.4.1-qlogic-hotfix-3 # ./install-hotfix.sh
+ '[' -f /etc/pit-release ']'
+ readarray -t EXPECTED_NCNS
++ grep -oP 'ncn-[mw]\d+' /etc/hosts
++ sort -u
+ '[' 14 = 0 ']'
./install-hotfix.sh: line 46: $1: unbound variable
```

unbound variable

---

CASMTRIAGE-5033/README.md
CASMTRIAGE-5033/install-hotfix.sh

The `create-kis-artifacts.sh` script is not safe for fully deployed systems.
Use `create-ims-initrd.sh`, this will not disrupt the running system.
We do need to comment out the lines in the `create-ims-initrd.sh` script that remove the kdump initrd, since we may end up needing that if catastrophy strikes and the system panics while running the hotfix. After the script is called, this restores the original copy of the script.
This was tested on mug, it safely updated the initrd in the right places.

CASMTRIAGE-6065 Use safer script

---

csm-1.5.0-noos-repo-CASMTRIAGE-6715/README.md
csm-1.5.0-noos-repo-CASMTRIAGE-6715/install-hotfix.sh
csm-1.5.0-noos-repo-CASMTRIAGE-6715/lib/install.sh
csm-1.5.0-noos-repo-CASMTRIAGE-6715/lib/setup-nexus.sh
csm-1.5.0-noos-repo-CASMTRIAGE-6715/lib/version.sh
csm-1.5.0-noos-repo-CASMTRIAGE-6715/nexus-repositories.template.yaml
csm-1.5.0-noos-repo-CASMTRIAGE-6715/rpm/index.yaml
release.sh

This adds a generalized hotfix for adding packages to the CSM 1.5 noos repository.
Initially, this includes spire-agent packages mentioned by CASMTRIAGE-6715.
The hotfix will download the current csm-1.5 noos repository (for any release it will resolve the member repository to the csm-noos repository group). Collate the hotfix's RPMs into the downloaded repository, update metadata, and then finally recreate the repository and repository group in nexus.

CASMTRIAGE-6715 Add packages to csm-noos

---

csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/README.md
csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/docker/index.yaml
csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/helm/index.yaml
csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/install-hotfix.sh
csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/lib/install.sh
csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/lib/setup-nexus.sh
csm-1.5.0-cray-hms-rts-CASMTRIAGE-6698/lib/version.sh

New hotfix published addressing CASMTRIAGE-6698 (originally CAST-34868)
* Resolves [CAST-34868](https://jira-pro.it.hpe.com:8443/browse/CAST-34868)
* Resolves [CASMTRIAGE-6698](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6698)
* Virtual Shasta
Before hotfix installation:
ncn-m001:~ # helm ls -n services | grep cray-hms-rts
cray-hms-rts                     	services 	1       	2024-03-05 18:23:53.446565465 +0000 UTC	deployed	cray-hms-rts-4.0.0                     	1.23.0
cray-hms-rts-snmp                	services 	1       	2024-03-05 22:34:12.80981102 +0000 UTC 	deployed	cray-hms-rts-4.0.0                     	1.23.0
After hotfix installation:
ncn-m001:~ # helm ls -n services | grep cray-hms-rts
cray-hms-rts                     	services 	2       	2024-03-06 00:50:03.474683356 +0000 …

CASMREL-1720 hotfix for CASMTRIAGE-6698

---

CASMTRIAGE-6716/README.md
CASMTRIAGE-6716/install-hotfix.sh
CASMTRIAGE-6716/lib/install.sh
CASMTRIAGE-6716/lib/setup-nexus.sh
CASMTRIAGE-6716/lib/version.sh
CASMTRIAGE-6716/nexus-repositories.template.yaml
CASMTRIAGE-6716/rpm/index.yaml

This is a bug fix for CASMTRIAGE-6716 . iuf not exiting with an error when failed.
Giving message "The stage failed, but argo must run to the completion of the stage." 
But not exiting with return code 1 after stage completion.
critical bug fix
It is a backwards compatible bugfix.
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6716
* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6554
* Local development environment (Starlord)
* Virtual Shasta(beau)
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
* yes
- Was upgrade tested? 
* yes
- Were new tests (or test issues/Jiras) created for this change?
* yes
_Are there known issues with these changes? Any other special considerations?_
No

CASMTRIAGE-6716

---

csm-1.5/CASMINST-6799-iuf-race-condition/README.md
csm-1.5/CASMINST-6799-iuf-race-condition/lib/install.sh

Hotfix dir for [CASMINST-6799](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6799) is missing `lib/install.sh` symlink to respective file in vendored directory. As a result, hotfix tarball is also missing this file, and hotfix is not installable without a workaround (which is to copy `lib/install.sh` from another hotfix).
* Resolves [CASMTRIAGE-6814](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6814)
* Local development environment
Rebuilt hotfix and ensured `lib/install.sh` is included.
Low - install scripts only.

CASMTRIAGE-6814: restore lib/install.sh for CASMINST-6799 hotfix

---

Jenkinsfile.github
release.sh
vendor/github.hpe.com/hpe/hpc-shastarelm-release/lib/release.sh

Use skopeo, rpm-tools, packaging-tools and cray-nexus-setup from artifactory.algol60.net.
* Resolves CASMINST-6835
* Jenkins
Made a temporary modification, which was already rolled back:
* Adjusted hotfix rebuild criteria to rebuild all 1.5.0 hotfixes
* Vendored https://github.hpe.com/hpe/hpc-shastarelm-release from temporary branch `feature/algol60-auth`
Rebuilt all hotfixes successfully within 2.5 minutes.
Low - build/install time change only.

CASMINST-6835 Use tools images from artifactory.algol60.net

---

csm-1.5/CASMTRIAGE-6796-csm-pre-install-metal-ipxe/README.md
csm-1.5/CASMTRIAGE-6796-csm-pre-install-metal-ipxe/install-hotfix.sh
csm-1.5/CASMTRIAGE-6796-csm-pre-install-metal-ipxe/lib/install.sh
csm-1.5/CASMTRIAGE-6796-csm-pre-install-metal-ipxe/lib/version.sh
csm-1.5/CASMTRIAGE-6796-csm-pre-install-metal-ipxe/rpm/index.yaml

Inserts a [new metal-ipxe](https://github.com/Cray-HPE/metal-ipxe/pull/77) into the CSM tarball.
This way the new metal-ipxe can be included in k8s-nexus, even though it's moot it's at least consistent.
This hotfix must be ran during a fresh install, immediately after the CSM tarball is extracted (this will be noted in the field notice, as well as docs-csm).

CASMTRIAGE-6796 New `metal-ipxe`

---

csm-1.5/CASMCMS-9097-bos-cfs-scale/README.md
csm-1.5/CASMCMS-9097-bos-cfs-scale/docker/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/helm/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/install-hotfix.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/install.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/setup-nexus.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/nexus-repositories.template.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/rpm/csm-noos/index.yaml

Basically the CSM 1.5 version of https://github.com/Cray-HPE/csm-hotfixes/pull/50
However, the exact contents are different, of course. 
I partially tested it on mug and wasp, but fully tested it on groot.

CASMCMS-9097: BOS/CFS scale patch for CSM 1.5

---

csm-1.4/CASMTRIAGE-5033/README.md
csm-1.4/CASMTRIAGE-5033/lib/version.sh
csm-1.4/CASMTRIAGE-5033/rpm/index.yaml

Use the newer, patched driver from Marvell.
`8.74.1.0_k5.14.21_150400.22-1.sles15sp4` contains the new breakthrough fixes developed by Marvell that result in successful network interface recovery during CPU stalls.

CASMTRIAGE-5033 Update

---

csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/README.md
csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/docker/index.yaml
csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/helm/index.yaml
csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/install-hotfix.sh
csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/lib/install.sh
csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/lib/setup-nexus.sh
csm-1.5/CASMTRIAGE-7166-tapms-tenants-deploying/lib/version.sh

Updates tapms to fix an issue that was preventing the status of tenants from getting to "deployed"
* Resolves CASMTRIAGE-7166
* Slice/Tyr
Most testing occured on Tyr, but the final hotfix patch test was deployed on Slice to validate it.
None

CASMTRIAGE-7166: Add hotfix for tapms tenant status

---

csm-1.5/CASMCMS-9097-bos-cfs-scale/README.md
csm-1.5/CASMCMS-9097-bos-cfs-scale/docker/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/helm/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/rpm/csm-noos/index.yaml

This updates the CSM 1.5 BOS scale hotfix to pull in fixes for two BOS bugs: [CASMCMS-9143](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9143) and [CASMCMS-9164](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9164). The former bug was fixed a while ago but wasn't significant enough to respin this hotfix, since it had no performance implications. However, the latter bug does impact BOS performance, and is probably more likely to be encountered at scale.

Update CSM 1.5 BOS hotfix to include fixes for bugs CASMCMS-9164 and CASMCMS-9143

---

csm-1.4/CASMCMS-9044-bos-cfs-scale/README.md
csm-1.4/CASMCMS-9044-bos-cfs-scale/docker/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/helm/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/lib/version.sh
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp2-compute/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp3-compute/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp4-compute/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp4/index.yaml

Same as https://github.com/Cray-HPE/csm-hotfixes/pull/58, but for CSM 1.4
This one also pulls in the fix for BOS bug [CASMCMS-9143](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9143)

Update CSM 1.4 BOS hotfix to include CASMCMS-9162 and CASMCMS-9165

---

csm-1.4/CASMCMS-9044-bos-cfs-scale/install-hotfix.sh
csm-1.4/CASMCMS-9044-bos-cfs-scale/lib/version.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/install-hotfix.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh

In my previous PRs, I failed to update the version numbers in the BOS scaling hotfix install scripts. This corrects that.

Correct version numbers in BOS scaling hotfix install scripts

---

csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/rpm/csm-noos/index.yaml

The CSM 1.5 BOS hotfix needs a newer version of the Cray CLI.

Update Cray CLI version in BOS hotfix

---

csm-1.5/CASMINST-7033-update-mgmt-ncn-cfs-config/README.md
csm-1.5/CASMINST-7033-update-mgmt-ncn-cfs-config/install-hotfix.sh
csm-1.5/CASMINST-7033-update-mgmt-ncn-cfs-config/lib/install.sh
csm-1.5/CASMINST-7033-update-mgmt-ncn-cfs-config/lib/version.sh
release.sh

Create a hotfix for CSM 1.5.1 and 1.5.2 to address the issue with the `update-mgmt-ncn-cfs-config.sh` script dropping the `additional_inventory` and `special_paremeters` in the CFS configuration assigned to management nodes.
* Resolves [CASMINST-7033](https://jira-pro.it.hpe.com:8443/browse/CASMINST-7033)
* Merge this PR before the docs-csm PR: https://github.com/Cray-HPE/docs-csm/pull/5498
* drax
* Copied the relevant portions of a CSM 1.5.2 release distribution that existed on drax to another directory. Relevant portions include the `update-mgmt-ncn-cfs-config.sh` script, the shell libraries in `lib/`, and the file `vendor/cfs-config-util.tar`.
* Built the hotfix tar file and copied to drax. Extracted it there.
* Followed the instructions in the `README.md` file in the hotfix directory …

CASMINST-7033: Create 1.5.{1,2} hotfix for `update-mgmt-ncn-cfs-config.sh`

---

csm-1.5/CASMCMS-9097-bos-cfs-scale/README.md
csm-1.5/CASMCMS-9097-bos-cfs-scale/docker/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/helm/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/install-hotfix.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh

Update the CSM 1.5 BOS/CFS scale hotfix with the following fixes/improvements:
* [CASMCMS-9196](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9196) - Fix CFS Exception when trying to create Source
* [CASMCMS-9197](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9197) - Bypass needless work in some CFS queries
* [CASMCMS-9198](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9198) - Prevent invalid option values from causing CFS CLBO
* [CASMCMS-9200](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9200) - Fix a thread safety bug and performance issue in CFS server
* [CASMCMS-9202](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9202) - Add CFS v3 API option to enable restoring Source data from backup
* [CASMCMS-9206](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9206) - Fix bug …

Update BOS/CFS 1.5 scale fix

---

csm-1.5/CASMCMS-9097-bos-cfs-scale/docker/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/helm/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/install-hotfix.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh

This updates the BOS/CFS scale hotfix to pull in a bugfix. The bug causes the CFS server to not start because it is stuck in CLBO. I am not listing the bugfix in the hotfix readme, because the bug was introduced in the previous iteration of the hotfix -- it is not present in CSM itself otherwise.
The problem is not present in the CSM 1.4 version of this hotfix.
I have tested this updated hotfix on hela (the system where the problem was reported) and verified that it resolves the issue.

CASMCMS-9219: Fix bug causing CFS server CLBO

---

csm-1.5/CASMCMS-9175-console-inotify-tools/install-hotfix.sh
csm-1.5/CASMCMS-9175-console-inotify-tools/lib/version.sh

There was a bug in the install script for the hotfix `CASMCMS-9175-console-inotify-tools` which prevented it from installing correctly. This resolves the issue and correctly uploads the new artifacts into nexus.
* Resolves [CASMTRIAGE-7526](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7526)
* `Hela`
I hand-applied the script change to the hotfix install directory on Hela and successfully executed the script.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? N
- Was upgrade tested? If not, why? N
- Was downgrade tested? If not, why? N
- Were new tests (or test issues/Jiras) created for this change? N
Low risk - fixing install script.

CASMTRIAGE-7526 - fix for CASMCMS-9175 hotfix install script.

---

csm-1.5/CASMCMS-9097-bos-cfs-scale/README.md
csm-1.5/CASMCMS-9097-bos-cfs-scale/docker/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/helm/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/install-hotfix.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh

The resource issues seen in PCS are particularly important to address on large scale systems. The BOS/CFS scale hotfix already includes an updated version of PCS in it, to pull in other fixes. This PR updates the hotfix to pull in these additional PCS fixes.
If the PCS fixes will also be of interest to non-scale customers, then probably a standalone hotfix for it should also be created.

Update CSM 1.5 BOS/CFS/PCS scale hotfix to include fix for CASMHMS-6299

---

csm-1.4/CASMCMS-9044-bos-cfs-scale/README.md
csm-1.4/CASMCMS-9044-bos-cfs-scale/docker/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/helm/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/install-hotfix.sh
csm-1.4/CASMCMS-9044-bos-cfs-scale/lib/version.sh
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp2-compute/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp3-compute/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp4-compute/index.yaml
csm-1.4/CASMCMS-9044-bos-cfs-scale/rpm/csm-sle-15sp4/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/README.md
csm-1.5/CASMCMS-9097-bos-cfs-scale/docker/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/helm/index.yaml
csm-1.5/CASMCMS-9097-bos-cfs-scale/install-hotfix.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/lib/version.sh
csm-1.5/CASMCMS-9097-bos-cfs-scale/rpm/csm-noos/index.yaml

This updates the BOS 1.4 and 1.5 hotfixes to pull in the latest fixes and improvements. UKMet is waiting on this.

CASMCMS-9242: Pull in latest BOS scale fixes/improvements

---

csm-1.5/CASMTRIAGE-7232-kdump/hotfix-running-system.sh
csm-1.5/CASMTRIAGE-7232-kdump/lib/version.sh

Resolves an issue with the runtime script from CASMTRIAGE-7232.
Tested changes to `hotfix-running-system.sh` in Vshasta on scanlan with CSM V1.5.2.

CASMTRIAGE-7689
